title: "@dp247"
title_separator: "|"
email: null
url: "https://dp247.github.io"
description: <3 Python
twitter_username: dp247
github_username: dp247
minimal_mistakes_skin: dark
search: true
search_provider: lunr
lunr:
  search_within_pages: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: GB
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
author:
  name: David Park
  avatar: /assets/images/bio-photo.jpg
  bio: "Avid gamer, writer of Python and C#. Works in data."
  location: "Leeds, UK"
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/dp247'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/dp247'
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: 'https://instagram.com/dp247'
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: 'https://twitter.com/dp247'
    - label: GitHub
      icon: fab fa-fw fa-github
      url: 'https://github.com/dp247'
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: 'https://instagram.com/dp247'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
# _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
